title:              Noise Pollution and Underprivileged Communities
email:              mvanbur@gmu.edu
description:        Visualizing Noise Pollution Reports and Underprivileged Communities
author:             mvanbur
baseurl:            "https://mvanbur.github.io"
url:                "https://mvanbur.github.io/HT_KC_DataScience"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
